# -*- coding: utf-8 -*-
"""gpt-devme.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgqeHtaabvdQYJpR1uPq5fCCtiZPsWCj

# Here we are going to train a language based transformer model

## lets first start with a small shakespear datset
"""

#!wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
import torch
import torch.nn as nn
from torch.nn import functional as F
max_iters = 3000
eval_itervals = 300
learning_rate = 1e-2
batch_size = 32
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
torch.manual_seed(1337)
with open ('input.txt', 'r', encoding = 'utf-8') as f:
  text = f.read()

# Length of dataset: -
print("length of dataset in characters= ", len(text))

#lets look at first 1000 text
print(text[:1000])

chars = sorted(list(set(text)))
vocab_size = len(chars)
print(vocab_size)
print(''.join(chars))

"""## performing tokenization:
here in tokenization we break raw text in to string characters to some sequence then map them to integers
### here we have implied simple tokenization instead of sub-tokenization to make the project look simple and easy to learn
"""

stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s] # encoder: take a string,output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take integer output a string
print((encode("hii there")))
print(decode(encode("hii there")))

"""## now lets encode the entire text dataset and store it to a tensor"""


data = torch.tensor(encode(text), dtype = torch.long)
print(data.shape, data.dtype)
print(data[:1000])

"""# seprate the training dataset and validation dataset"""

n = int(0.9*len(data))
train_data = data[:n]
val_data = data[n:]

"""## now instead of loading the complete dataset to transformer we divide it into chunks here i have set the block size to 8 to feed to the transformer"""

block_size = 8
train_data[:block_size+1]

x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
  context = x[:t+1]
  target = y[t]
  print(f"when input is {context} then output is {target}")

"""### now lets generalizing and introduce a batch dimension to maximize computational efficiency on modern hardware (GPUs/TPUs) and to stabilize the learning process. By grouping multiple sequences together—the "batch dimension"—the model processes data in parallel rather than sequentially, which significantly speeds up training and provides a more stable estimate of the gradient."""

torch.manual_seed(1337) #in random number generator we set seed to a particular integer to maintain th reproducability of the transformer
batch_size = 4
block_size = 8
def get_batch(split):# generate small batch of data of input x and target y
  data = train_data if split == 'train' else val_data
  ix = torch.randint(len(data) - block_size, (batch_size,))
  x = torch.stack([data[i:i+block_size] for i in ix])
  y = torch.stack([data[i+1:i+block_size+1] for i in ix])
  x,y = x.to(device), y.to(device)
  return x,y
@torch.no_grad()#here no backpropagation is required
def estimate_loss():
  out = {}
  model.eval()
  for split in ['train','val']:
    losses = torch.zeros(eval_iters)
    for k in range(eval_iters):
      xb,yb = get_batch(split)
      logits,loss = model(xb,yb)
      losses[k] = loss.item()
    out[split] = losses.mean()
  model.train()
  return out


class BigramLanguageModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size,vocab_size)
  def forward(self,idx,targets= None):
    logits = self.token_embedding_table(idx)
    if targets is None:
      loss = None
    else:
      B, T, C = logits.shape
      logits = logits.view(B*T, C)
      targets = targets.view(B*T)
      loss = F.cross_entropy(logits, targets)
    return logits,loss
  def generate(self,idx,max_new_tokens):
    for _ in range(max_new_tokens):
      logits, loss = self(idx)
      logits = logits[:,-1,:]
      probs = F.softmax(logits,dim= -1)
      idx_next = torch.multinomial(probs,num_samples=1)
      idx = torch.cat((idx,idx_next),dim=1)
      idx = idx.to(device)
    return idx

model = BigramLanguageModel(vocab_size)
m = model.to(device)

optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)
for iter in range(max_iters):
  if iter % eval_itervals==0:
    losses  = estimate_loss()
    print(f"step {iter}: train loss {losses['train']:.4f}val loss {losses['val']:.4f}")
  xb,yb = get_batch('train')
  logits, loss = m(xb,yb)
  optimizer.zero_grad(set_to_none = True)
  loss.backward()
  optimizer.step()
print(loss.item())
context = torch.zeros((1,1),dtype= torch.long,device= device)
print(decode(m.generate(context,max_new_tokens = 500)[0].tolist()))
